version: '3.9'

networks:
  app-network:
    driver: bridge
  opensearch-net:
    driver: bridge

volumes:
  postgres-data:
  kafka-data:
  opensearch-data1:
  opensearch-data2:

services:
  app-spring:
    image: be-app-spring:0.0.1
#    container_name: marketplace-http
    ports:
      - "8080:8080"
    environment:
      DB_TYPE_PROD: "psql"
      MKPLADS_HOST: "psql"
      MKPLADS_PORT: 5432
      MKPLADS_DB: "cars_ads"
      MKPLADS_USER: "postgres"
      MKPLADS_PASS: "car-pass"
      THC_PATH: "/actuator/health"
      LOGS_FB_HOSTS: "fluent-bit"  # вместо 127.0.0.1
      LOGS_FB_PORT: "24224"
      SERVICE_NAME: "spring-app"

    depends_on:
      psql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/workspace/health-check"]
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
#        fluentd-address: localhost:24224
        fluentd-address: fluent-bit:24224
        tag: "spring-app"
        fluentd-async: "true"

  psql:
    image: postgres
#    container_name: marketplace-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "car-pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "cars_ads"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready" ]
      test: [ "CMD-SHELL", "pg_isready -U postgres -d cars_ads" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluent-bit:24224
        fluentd-address: localhost:24224
        tag: "postgres"
        fluentd-async: "true"

  liquibase:
    image: "other-migration-pg"
#    container_name: marketplace-liquibase
    environment:
      LIQUIBASE_URL:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://psql:5432/cars_ads
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: "car-pass"
      LIQUIBASE_LIQUIBASE_SCHEMA_NAME: public


    depends_on:
      psql:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224
        tag: "liquibase"
        fluentd-async: "true"

  # Kafka (KRaft mode)
  kafka:
    image: apache/kafka:latest
#    container_name: marketplace-kafka
    user: root
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#    volumes:
#      - kafka-data:/tmp/kraft-combined-logs
    healthcheck:
#      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      test: ["CMD", "bash", "-c", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluent-bit:24224
        fluentd-address: localhost:24224
        tag: "kafka"
        fluentd-async: "true"

  # Kafka UI (для мониторинга)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
#    container_name: marketplace-kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
        fluentd-address: fluent-bit:24224
        tag: "kafka-ui"
        fluentd-async: "true"

  app-kafka-consumer:
#    image: com.github.watching1981/be-app-kafka:0.0.1
    image: be-app-kafka:0.0.1
#    container_name: marketplace-kafka-consumer
    depends_on:
      kafka:
        condition: service_healthy
      psql:
        condition: service_healthy
    environment:
      # Kafka настройки
      KAFKA_HOSTS: kafka:19092
      KAFKA_GROUP_ID: car-market-consumer-group
      KAFKA_TOPIC_IN_V1: cars-ad-v1-in
      KAFKA_TOPIC_OUT_V1: cars-ad-v1-out

      MKPLADS_HOST: psql
      MKPLADS_PORT: 5432
      MKPLADS_DB: cars_ads
      MKPLADS_USER: postgres
      MKPLADS_PASS: car-pass
    networks:
      - app-network
    logging:
      driver: fluentd
      options:
#        fluentd-address: fluent-bit:24224
        fluentd-address: localhost:24224
        tag: "kafka-consumer"
        fluentd-async: "true"

  # ========== НОВЫЕ СЕРВИСЫ ДЛЯ ЛОГИРОВАНИЯ ==========

  opensearch:
    image: opensearchproject/opensearch:latest
#    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node  # ВАЖНО: режим одного узла!
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Joker_1981
      - DISABLE_SECURITY_PLUGIN=false
      - plugins.security.disabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    healthcheck:
#      test: ["CMD", "curl", "-f", "-k", "https://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=1s"]
      test: ["CMD", "curl", "-f", "-k", "-u", "admin:Joker_1981", "https://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: localhost:24224
#        tag: "opensearch"
#        fluentd-async: "true"

  # OpenSearch Dashboards (веб-интерфейс)
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
#    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
      OPENSEARCH_SSL_VERIFICATION: false
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "false"
    networks:
      - opensearch-net
    depends_on:
      opensearch:
        condition: service_healthy
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: localhost:24224
#        tag: "opensearch-dashboards"
#        fluentd-async: "true"

  # Fluent Bit для сбора логов (без изменений)
  fluent-bit:
    image: fluent/fluent-bit:latest
#    container_name: fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5170:5170"
      - "2020:2020"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
    networks:
      - app-network
      - opensearch-net
    depends_on:
      opensearch:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224
        tag: "fluent-bit"
        fluentd-async: "true"

