version: '3.9'

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  kafka-data:

services:
  app-spring:
    image: be-app-spring:0.0.1
    container_name: marketplace-http
    ports:
      - "8080:8080"
    environment:
      DB_TYPE_PROD: "psql"
      MKPLADS_HOST: "psql"
      MKPLADS_PORT: 5432
      MKPLADS_DB: "cars_ads"
      MKPLADS_USER: "postgres"
      MKPLADS_PASS: "car-pass"
      THC_PATH: "/actuator/health"
    depends_on:
      psql:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/workspace/health-check"]
    networks:
      - app-network
  psql:
    image: postgres
    container_name: marketplace-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "car-pass"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "cars_ads"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  liquibase:
    image: "other-migration-pg"
    container_name: marketplace-liquibase
    environment:
      LIQUIBASE_URL:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://psql:5432/cars_ads
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: "car-pass"
      LIQUIBASE_LIQUIBASE_SCHEMA_NAME: public


    depends_on:
      psql:
        condition: service_healthy
    networks:
      - app-network

  # Kafka (KRaft mode)
  kafka:
    image: apache/kafka:latest
    container_name: marketplace-kafka
    user: root
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:19092'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#    volumes:
#      - kafka-data:/tmp/kraft-combined-logs
    healthcheck:
#      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      test: ["CMD", "bash", "-c", "nc -z localhost 9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - app-network

  # Kafka UI (для мониторинга)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: marketplace-kafka-ui
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network

  app-kafka-consumer:
#    image: com.github.watching1981/be-app-kafka:0.0.1
    image: be-app-kafka:0.0.1
    container_name: marketplace-kafka-consumer
    depends_on:
      kafka:
        condition: service_healthy
      psql:
        condition: service_healthy
    environment:
      # Kafka настройки
      KAFKA_HOSTS: kafka:19092
      KAFKA_GROUP_ID: car-market-consumer-group
      KAFKA_TOPIC_IN_V1: cars-ad-v1-in
      KAFKA_TOPIC_OUT_V1: cars-ad-v1-out

      MKPLADS_HOST: psql
      MKPLADS_PORT: 5432
      MKPLADS_DB: cars_ads
      MKPLADS_USER: postgres
      MKPLADS_PASS: car-pass
    networks:
      - app-network