# Минимальная версия инфраструктуры на базе
# OpenSearch - хранилище логов и метрик
# OpenSearch Dashboards - отрисовка логов
# Fluent Bit - служба сбора логов
# Envoy - прокси
# Keycloak - сервер идентификации

# Адреса:
# Приложение доступно по http://localhost:8080 (envoy прокси)
# Панели мониторинга http://localhost:5601 (opensearch dashboards, kibana)
# Управление пользователями http://localhost:8080/admin (keycloak)

services:

  app:
    image: nginx:latest
    depends_on:
      - fluent-bit
      - envoy
    volumes:
      - ./volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/nginx/html:/usr/share/nginx/html
    logging:
      # используемый драйвер логгирования
      driver: "fluentd"
      options:
        # куда посылать лог-сообщения, необходимо чтобы адрес
        # совпадал с настройками плагина forward
        fluentd-address: localhost:24224
        # теги используются для маршрутизации лог-сообщений, тема
        # маршрутизации будет рассмотрена ниже
        tag: app.logs

  fluent-bit:
    #    Logstash: 2GB RAM 400MB Docker
    #    fluent-bit: 30MB Docker 30MB RAM
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      # необходимо открыть порты, которые используются плагином forward
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    environment:
      - opensearch_host=opensearch
      - opensearch_user=admin
      - opensearch_pass=adm-Password0
    volumes:
      - ./volumes/fluent-bit-etc/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./volumes/fluent-bit-etc/parsers.conf:/fluent-bit/etc/parsers.conf

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=adm-Password0
    ports:
      - '9200:9200'
      - '9600:9600'
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -ku admin:adm-Password0 https://localhost:9200/_cluster/health?pretty | grep status | grep -q '\\(green\\|yellow\\)'"
        ]
      interval: 5s
      timeout: 5s
      retries: 24
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  #    volumes:
  #      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      opensearch:
        condition: service_healthy

  envoy:
    image: envoyproxy/envoy:v1.29.0  # Use the official Envoy proxy image
    volumes:
      - ./volumes/envoy/envoy.yaml:/etc/envoy/envoy.yaml  # Mount your Envoy configuration file
    #      - ./envoy/certs:/etc/envoy/certs  # Mount your TLS certificates
    ports:
      - "8080:8080"
    depends_on:
      keycloak:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    ports:
      - "8081:8080"
    volumes:
      - ./volumes/keycloak/import:/opt/keycloak/data/import
    #      - ./keycloak/standalone.xml:/opt/jboss/keycloak/standalone/configuration/standalone.xml
    #      - ./keycloak/certs/keycloak.jks:/etc/x509/https/keystore  # Mount your Keycloak keystore
    environment:
      KEYCLOAK_USER: filippovma
      KEYCLOAK_PASSWORD: test
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KEYCLOAK_IMPORT: "/tmp/realm-export.json"
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'HEAD /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3"]
      interval: 10s
      timeout: 5s
      retries: 15
    command:
      - start-dev
      - --import-realm
      - --hostname-strict
      - "false"
      - --hostname
      - "http://localhost:8080/"
      - --proxy-headers
      - forwarded
      - --hostname-backchannel-dynamic
      - "true"

volumes:
  opensearch-data:
