# This is a basic workflow to help you get started with Actions

name: 'CI-build'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
      - 'master'
      - 'm*'
      - 'release/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-24.04
    #    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#          token: ${{ secrets.PAT_TOKEN }}

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .gradle
            .kotlin
          key: ${{ runner.os }}-primes

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      #      - name: Validate Gradle wrapper
      #        uses: gradle/wrapper-validation-action@v1

      #      # https://github.com/actions/runner-images/issues/675
      #      - name: Hack sources.list
      #        run: sudo sed -i 's|http://azure.archive.ubuntu.com/ubuntu/|http://mirror.arizona.edu/ubuntu/|g' /etc/apt/sources.list
      #
      #      - name: Install curl-dev
      #        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libpq-dev libpq5

      - name: Build Migrations
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.14.1
          arguments: buildMigrations --info
      - name: Build Main Images
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.14.1
          arguments: buildImages --info
      - name: Run E2E tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.14.1
          arguments: e2eTests --info

      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            .gradle
            .kotlin
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
